version: '3'

services:
  fleet:
    image: kolide/fleet
    command: sh -c "echo '\n' | /usr/bin/fleet prepare db --config=/tmp/fleet.yml && /usr/bin/fleet serve --config=/tmp/fleet.yml"
    volumes:
      - .:/tmp
    ports:
      - "8080:8080"
    networks:
      - fleet-net
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql
    command: mysqld --datadir=/tmp/mysqldata --slow_query_log=1 --log_output=TABLE --log-queries-not-using-indexes --event-scheduler=ON
    volumes:
      - mysql-data:/tmp
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: kolide
      MYSQL_USER: kolide
      MYSQL_PASSWORD: kolide
    networks:
      - fleet-net

  redis:
    image: redis
    networks:
      - fleet-net

volumes:
  mysql-data:

networks:
  fleet-net:
